To-DO
Sudhakar Sharma (Sudhakar Sharma Naresh IT)
•
Yesterday
TO-DO APP

   

   1. User can register and login

   2. User gets dashboard after login 

   3. Dashboard comprises of user appointments

       - User can add appointment

       - Edit appointment 

       - Delete appointment

       - Filter, Sort, Search 

       

   Data Model for TO-DO

   

   1. Users 

           - user_id            : string     [PK]

           - user_name        : string

           - password        : string

           - email                : string 



   2. Appointments

           - appointment_id    : number / autogenerated_key  [PK]

           - title                        : string

           - description            : string

           - date                    : date

           - user_id                : string [Users] [FK]



   JSON SERVER 

   - It maintains data and API.

   - Data is maintained in JSON file. 

   - API provides end points to interact with data. 



   1. Create a new project using React Vite bundler 



           > npm  create  vite@latest    react-todo-7PM



                   Framework        : React

                   Variant                : Javascript 



   2. Open Project folder in VS code



   3. Install JSON SERVER



           > npm install  json-server --save 



   4. Add a new file by name “db.json” in project root folder 



           {

               “users”: [ ],

               “appointments”: [ ]

           }

   

   5. Start JSON API SERVER 

   

           > npx  json-server  db.json 



           http://localhost:3000/users

           http://localhost:3000/appointments 



   6. To start API every time in project you can set shortcut in package.json 

   

           “scripts”: {

                   ……. ,

                   “api”:  “npx json-server db.json”

           }

           

           > npm run api



       API END POINTS:

       

       GET            /users                    returns all users [ ]

       GET            /users/id                returns specific user { }

       POST        /users                    add new user into DB

       PUT            /users/id                update specific user 

       DELETE    /users/id                remover specific user 



       GET            /appointments

       GET            /appointments/id

       POST        /appointments

       PUT            /appointments/id

       DELETE    /appointments/id



       Note: Download and Install “POSTMAN” web debugger to test API methods.

                           

    Setup UI for TO-DO:

    1. Install following libraries 



           > npm install bootstrap  bootstrap-icons --save 

           > npm install axios   formik  yup  moment --save

           > npm install react-cookie  react-router-dom --save 



   2. High Level Flow



           Home => User Register / Login => Dashboard => CRUD => Signout 



   3. Add following components



           - todo-home.jsx

           - todo-login.jsx

           - todo-register.jsx

           - user-dashboard.jsx
Class comments
